### ISSUE TITLE
FIMS Validation Errors Megathread

### ISSUE THREAD

**Issue by tigerhawkvok** [AmphibiaWeb/amphibian-disease-tracker#61]
Headers respond with

```
HTTP/1.1 415 Unsupported Media Type
X-FRAME-OPTIONS: DENY
Content-Type: text/html;charset=UTF-8
Content-Length: 6186
Server: Jetty(9.2.6.v20141205)
```

for file

```
"@/usr/local/web/amphibiaweb_disease/helpers/js-dragdrop/uploaded/61146e64d2d76f7bd6f08e857e221236/442e8de5d9b3c91a97eb6d626d1ea67c.xlsx;filename=442e8de5d9b3c91a97eb6d626d1ea67c.xlsx;type=application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
```

I thought Office documents were allowed? Do I need to fake-out the MIME type `application/vnd.openxmlformats-officedocument.spreadsheetml.sheet` into something else? Leave it off?

**Comment by jdeck88** [comment]
if the request isn't sent with the mediatype 'multipart/form-data' a 415 response will be returned. with cURL you need to use "-F" for the form data vs "-d"

**Comment by tigerhawkvok** [comment]
Hm, that'll need some looking at, then, because that was how it was sent:



Clearly being overridden in the next few options (maybe the explicit post
declaration), time to play with the orders. I somehow parsed "media type"
as "media mime type", sorry!



On Tue, Mar 8, 2016, 07:00 John Deck <notifications@github.com> wrote:

> Closed #61
> <https://github.com/AmphibiaWeb/amphibian-disease-tracker/issues/61>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AmphibiaWeb/amphibian-disease-tracker/issues/61#event-581829935>
> .
>
-- 


-via Nexus 6P-

---------------------------
Philip Kahn
1314 Hopkins St
Berkeley CA
94702
510.859.3142
---------------------------

**Comment by tigerhawkvok** [comment]
Well, improved it to a Server Error

```json
{
  "stackTrace": "java.lang.NullPointerException
    at services.rest.Validate.validate(Validate.java:95)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
    at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
    at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
    at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)
    at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
    at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
    at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
    at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
    at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
    at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
    at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
    at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
    at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
    at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
    at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:471)
    at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:425)
    at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:383)
    at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:336)
    at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:223)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
    at services.RedirectFilter.doFilter(RedirectFilter.java:29)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
    at biocode.fims.rest.filters.ClickJackFilter.doFilter(ClickJackFilter.java:28)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
    at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
    at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
    at org.eclipse.jetty.server.Server.handle(Server.java:497)
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:313)
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
    at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:626)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:546)
    at java.lang.Thread.run(Thread.java:745)",
  "developerMessage": "",
  "httpStatusCode": 500,
  "usrMessage": "Server Error",
  "time": "2016-03-08 12:30:47.886",
  "exceptionMessage": null
}

```

**Comment by jdeck88** [comment]
inserted a null condition statement in fims code and redeployed with commit
https://github.com/biocodellc/biscicol-fims/commit/966e5e446228ff94d64207db3a3e442c5e72f166

i didn't test/reproduce your error so not positive this work but pretty
sure this fix will take care of the error.

On Tue, Mar 8, 2016 at 9:33 AM, Philip Kahn <notifications@github.com>
wrote:

> Reopened #61
> <https://github.com/AmphibiaWeb/amphibian-disease-tracker/issues/61>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AmphibiaWeb/amphibian-disease-tracker/issues/61#event-582065757>
> .
>



-- 
John Deck
(541) 914-4739

**Comment by tigerhawkvok** [comment]
OK, I can't take a look at it till late tonight, but I'll update then.

On Tue, Mar 8, 2016, 10:09 John Deck <notifications@github.com> wrote:

> inserted a null condition statement in fims code and redeployed with commit
>
> https://github.com/biocodellc/biscicol-fims/commit/966e5e446228ff94d64207db3a3e442c5e72f166
>
> i didn't test/reproduce your error so not positive this work but pretty
> sure this fix will take care of the error.
>
> On Tue, Mar 8, 2016 at 9:33 AM, Philip Kahn <notifications@github.com>
> wrote:
>
> > Reopened #61
> > <https://github.com/AmphibiaWeb/amphibian-disease-tracker/issues/61>.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/AmphibiaWeb/amphibian-disease-tracker/issues/61#event-582065757
> >
> > .
> >
>
>
>
> --
> John Deck
> (541) 914-4739
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AmphibiaWeb/amphibian-disease-tracker/issues/61#issuecomment-193896026>
> .
>
-- 


-via Nexus 6P-

---------------------------
Philip Kahn
1314 Hopkins St
Berkeley CA
94702
510.859.3142
---------------------------

**Comment by tigerhawkvok** [comment]
Throwing it a small dataset worked just perfectly, giving

```json
    "validate_response": {
      "done": {
        "0": {
          "Samples": {
            "warnings": null,
            "errors": {
              "0": {
                "Spreadsheet check": {
                  "0": "Unable to find a required worksheet named 'Samples' (no quotes)"
                }
              }
            }
          }
        }
      }
    }
```

but a large one gave

```html
      <div class="alert-container"><div id="alerts"></div></div> 
      <div class="section"> 
        <div class="sectioncontent"> 
          <h1>HTTP ERROR </h1> 
          <br> 
          <p>Problem accessing /biocode-fims/rest/validate. Reason:</p> 
          <p>&emsp;&emsp;</p> 
        </div> 
      </div> 
 ```

(Along with the rest of the HTML doc)

**Comment by tigerhawkvok** [comment]
I take it back, the small one crapped out again when I fixed the worksheet name, same (non) error.

**Comment by jdeck88** [comment]
Philip,
can you post the sample dataset that crapped out?  I'll use it to debug
what is happening.

John

On Wed, Mar 9, 2016 at 2:53 PM, Philip Kahn <notifications@github.com>
wrote:

> I take it back, the small one crapped out again when I fixed the worksheet
> name, same (non) error.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AmphibiaWeb/amphibian-disease-tracker/issues/61#issuecomment-194553293>
> .
>



-- 
John Deck
(541) 914-4739

**Comment by jdeck88** [comment]
Also, i made some adjustments to java memory settings for jetty.  PermGen space complaints.  I made this much larger... This has been causing some errors recently and may be related to your error.  try it out and see if it works for you.

**Comment by tigerhawkvok** [comment]
Yep, seems to be fixed! Getting correct responses now, and the big dataset is giving responses and the small dataset validated and everything. 

I'll email you datasheet, though, that's giving this for reasons I don't understand -- [Here's a restricted Google Drive copy of the file (you'll need to be logged in to view this)](https://drive.google.com/file/d/0B6LJvOj7KC-cSTFPZnM3dmFxV2M/view?usp=sharing), which is returning:

```json
{
  "done": {
    "0": {
      "Samples": {
        "warnings": null,
        "errors": {
          "0": {
            "Initial Spreadsheet check": {
              "0": "Unable to parse spreadsheet.  This is most likely caused by having two columns with the same name.  Please rename or delete the extra column to pass validation."
            }
          }
        }
      }
    }
  }
}
```

I'd also comment that maybe some variations on "Bd" and "Bsal" should be OK, but I'd like @mkoo 's opinion on this (I'd think full scientific + "B.d." and "B. d." should also be allowed)

**Comment by tigerhawkvok** [comment]
Never mind, I'm blind

**Comment by jdeck88** [comment]
wait, i'm confused... the attached spreadsheet returns the following
(doesn't match what you sent).

(and, by the way, its complaining about the "non-valid URI characters"
since there is a rule in place that checks for problematic characters that
could become part of an HTTP URI, such as a space):



{"done": [{"Samples":{"errors":[{"Non-valid URI
characters":["\"fieldNumber\" contains some bad characters: GFMJ 1000, GFMJ
1001, GFMJ 1002, GFMJ 1003, GFMJ 1004, GFMJ 1005, GFMJ 1006, GFMJ 1012,
GFMJ 1013, GFMJ 1014, GFMJ 1015, GFMJ 1016, GFMJ 1017, GFMJ 1018, GFMJ
1019, GFMJ 1020, GFMJ 1024, GFMJ 1025, GFMJ 1026, GFMJ 1027, GFMJ 1028,
GFMJ 1029, GFMJ 1030, GFMJ 1031, GFMJ 1032, GFMJ 1033, GFMJ 1058, GFMJ
1059, GFMJ 1060, GFMJ 1061, GFMJ 1062, GFMJ 1063, GFMJ 1064, GFMJ 1065,
GFMJ 1066, GFMJ 1067, GFMJ 1068, GFMJ 1069, GFMJ 1070, GFMJ 1071, GFMJ
1072, GFMJ 1074, GFMJ 1075, GFMJ 1076, GFMJ 1077, GFMJ 1079, GFMJ 1080,
GFMJ 1081, GFMJ 1083, GFMJ 1084, GFMJ 1085, GFMJ 1086, GFMJ 1087, GFMJ
1088, GFMJ 1089, GFMJ 1090, GFMJ 1091, GFMJ 1092, GFMJ 1093, GFMJ 1094,
GFMJ 1095, GFMJ 1096, GFMJ 1097, GFMJ 1098, GFMJ 1099, GFMJ 1100, GFMJ
1101, GFMJ 1102, GFMJ 1103, GFMJ 1104, GFMJ 1105, GFMJ 1106, GFMJ 1108,
GFMJ 1109, GFMJ 1110, GFMJ 1111, GFMJ 1112, GFMJ 1113, GFMJ 1114, GFMJ
1115, GFMJ 1116, GFMJ 1117, GFMJ 1118, GFMJ 1120, GFMJ 1121, GFMJ 1122,
GFMJ 1172, GFMJ 1173, GFMJ 1174, GFMJ 1175, GFMJ 1176, GFMJ 1177, GFMJ
1178, GFMJ 1179, GFMJ 1180, GFMJ 1181, GFMJ 1182, GFMJ 1183, GFMJ 1184,
GFMJ 1185, GFMJ 1186, GFMJ 1187, GFMJ 1188, GFMJ 1189, GFMJ 1190, GFMJ
1192, GFMJ 1193, GFMJ 1194, GFMJ 1195, GFMJ 1196, GFMJ 1197, GFMJ 1198,
GFMJ 1199, GFMJ 1200, GFMJ 1201, GFMJ 1202, GFMJ 1203, GFMJ 1204, GFMJ
1205, GFMJ 1206, GFMJ 1207, GFMJ 1208, GFMJ 1209, GFMJ 1211, GFMJ 1212,
GFMJ 1214, GFMJ 1215, GFMJ 1216, GFMJ 1217, GFMJ 1218, GFMJ 1219, GFMJ
1220, GFMJ 1221, GFMJ 1222, GFMJ 1223, GFMJ 1225, GFMJ 1226, GFMJ 1227,
GFMJ 1228, GFMJ 1229, GFMJ 1230, GFMJ 1239, GFMJ 1240, GFMJ 1241, GFMJ
1243, GFMJ 1244, GFMJ 1246, GFMJ 1247, GFMJ 1248, GFMJ 1249, GFMJ 1281,
GFMJ 1282, GFMJ 1283, GFMJ 1284, GFMJ 1285, GFMJ 1286, GFMJ 1287, GFMJ
1288, GFMJ 1289, GFMJ 1290, GFMJ 1291, GFMJ 1292, GFMJ 1293, GFMJ 1294,
GFMJ 1297, GFMJ 1298, GFMJ 1299, GFMJ 1300, GFMJ 1301, GFMJ 1302, GFMJ
1303, GFMJ 1304, GFMJ 1305, GFMJ 1306, GFMJ 1307, GFMJ 1308, GFMJ 1309,
GFMJ 1310, GFMJ 1312, GFMJ 1314, GFMJ 1315, GFMJ 1317, GFMJ 1318, GFMJ
1319, GFMJ 1320, GFMJ 1321, GFMJ 1322, GFMJ 1323, GFMJ 1324, GFMJ 1325,
GFMJ 1326, GFMJ 1327, GFMJ 1328, GFMJ 1329, GFMJ 1330, GFMJ 1331, GFMJ
1332, GFMJ 1333, GFMJ 1334, GFMJ 1335, GFMJ 1336, GFMJ 1337, GFMJ 1338,
GFMJ 1339, GFMJ 1340, GFMJ 1341, GFMJ 1368, GFMJ 1372, GFMJ 1373, GFMJ
1374, GFMJ 1375, GFMJ 1376, GFMJ 1377, GFMJ 1515, GFMJ 1556, GFMJ 1557,
GFMJ 1558, GFMJ 1559, GFMJ 1560, GFMJ 1561, GFMJ 1562, GFMJ 1563, GFMJ
1565, GFMJ 1566, GFMJ 1568, GFMJ 1569, GFMJ 1570, GFMJ 1571, GFMJ 1572,
GFMJ 1574, GFMJ 1575, GFMJ 1577, GFMJ 1578, GFMJ 1579, GFMJ 1580, GFMJ
1581, GFMJ 1582, GFMJ 1584, GFMJ 958, GFMJ 959, GFMJ 960, GFMJ 961, GFMJ
962, GFMJ 963, GFMJ 964, GFMJ 965, GFMJ 966, GFMJ 967, GFMJ 968, GFMJ 969,
GFMJ 970, GFMJ 971, GFMJ 972, GFMJ 973, GFMJ 974, GFMJ 976, GFMJ 977, GFMJ
978, GFMJ 979, GFMJ 980, GFMJ 983, GFMJ 984, GFMJ 986, GFMJ 987, GFMJ 988,
GFMJ 989, GFMJ 990, GFMJ 991, GFMJ 992, GFMJ 993, GFMJ 994, GFMJ 995, GFMJ
996, GFMJ 997, GFMJ 998, GFMJ 999, ORB 01, ORB 04, ORB 05, ORB 06, ORB 07,
ORB 09, ORB 10, ORB 102, ORB 103, ORB 104, ORB 105, ORB 106, ORB 107, ORB
108, ORB 109, ORB 11, ORB 110, ORB 111, ORB 12, ORB 13, ORB 137, ORB 14,
ORB 15, ORB 159, ORB 16, ORB 160, ORB 161, ORB 164, ORB 165, ORB 166, ORB
167, ORB 168, ORB 169, ORB 17, ORB 170, ORB 171, ORB 172, ORB 173, ORB 174,
ORB 175, ORB 177, ORB 178, ORB 18, ORB 181, ORB 182, ORB 183, ORB 184, ORB
185, ORB 186, ORB 188, ORB 189, ORB 19, ORB 190, ORB 191, ORB 192, ORB 193,
ORB 194, ORB 195, ORB 196, ORB 197, ORB 198, ORB 199, ORB 20, ORB 200, ORB
201, ORB 202, ORB 203, ORB 204, ORB 205, ORB 206, ORB 207, ORB 208, ORB 21,
ORB 22, ORB 23, ORB 24, ORB 247, ORB 248, ORB 249, ORB 25, ORB 250, ORB
251, ORB 252, ORB 253, ORB 254, ORB 255, ORB 256, ORB 257, ORB 258, ORB
259, ORB 26, ORB 260, ORB 261, ORB 264, ORB 265, ORB 266, ORB 268, ORB 269,
ORB 27, ORB 270, ORB 28, ORB 29, ORB 30, ORB 302, ORB 303, ORB 304, ORB
305, ORB 306, ORB 307, ORB 308, ORB 309, ORB 31, ORB 310, ORB 311, ORB 312,
ORB 313, ORB 314, ORB 315, ORB 316, ORB 317, ORB 318, ORB 319, ORB 32, ORB
320, ORB 321, ORB 322, ORB 323, ORB 324, ORB 330, ORB 331, ORB 332, ORB
333, ORB 334, ORB 335, ORB 336, ORB 337, ORB 338, ORB 339, ORB 340, ORB
341, ORB 342, ORB 35, ORB 359, ORB 36, ORB 360, ORB 361, ORB 362, ORB 363,
ORB 364, ORB 365, ORB 366, ORB 396, ORB 397, ORB 399, ORB 40, ORB 400, ORB
401, ORB 402, ORB 403, ORB 405, ORB 406, ORB 407, ORB 41, ORB 410, ORB 414,
ORB 415, ORB 417, ORB 419, ORB 42, ORB 420, ORB 421, ORB 423, ORB 425, ORB
426, ORB 427, ORB 429, ORB 43, ORB 44, ORB 45, ORB 46, ORB 47, ORB 48, ORB
49, ORB 50, ORB 51, ORB 52, ORB 53"]}],"warnings":[{"Missing
column(s)":["\"dilutionFactor\" has a missing cell value","Did not find
desirable columns: \"cycleTimeFirstDetection\""]}]}}]}

On Thu, Mar 10, 2016 at 4:48 PM, Philip Kahn <notifications@github.com>
wrote:

> Yep, seems to be fixed! Getting correct responses now, and the big dataset
> is giving responses and the small dataset validated and everything.
>
> I'll email you datasheet, though, that's giving this for reasons I don't
> understand -- Here's a restricted Google Drive copy of the file (you'll
> need to be logged in to view this)
> <https://drive.google.com/file/d/0B6LJvOj7KC-cSTFPZnM3dmFxV2M/view?usp=sharing>,
> which is returning:
>
> {
>   "done": {
>     "0": {
>       "Samples": {
>         "warnings": null,
>         "errors": {
>           "0": {
>             "Initial Spreadsheet check": {
>               "0": "Unable to parse spreadsheet.  This is most likely caused by having two columns with the same name.  Please rename or delete the extra column to pass validation."
>             }
>           }
>         }
>       }
>     }
>   }
> }
>
> I'd also comment that maybe some variations on "Bd" and "Bsal" should be
> OK, but I'd like @mkoo <https://github.com/mkoo> 's opinion on this (I'd
> think full scientific + "B.d." and "B. d." should also be allowed)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AmphibiaWeb/amphibian-disease-tracker/issues/61#issuecomment-195120566>
> .
>



-- 
John Deck
(541) 914-4739

**Comment by tigerhawkvok** [comment]
Yeah, I'm blind, I didn't actually see the duplicated column, you can ignore this. Working perfectly!

**Comment by jdeck88** [comment]
yea!
