### ISSUE TITLE
Datasets should be associated with expeditions

### ISSUE THREAD

**Issue by tigerhawkvok** [AmphibiaWeb/amphibian-disease-tracker#62]
As per https://fims.readthedocs.org/en/latest/amphibian_disease_example.html#mint-bcid . 

Last block on #56.

**Comment by tigerhawkvok** [comment]
Current implementation just returns a response `null`.

**Comment by tigerhawkvok** [comment]
@jdeck88 , head's-up, getting `HTTP 500` error from FIMS, with the following stack trace if a `null` or empty bcid is posted:

```java
java.lang.NullPointerException
    at biocode.fims.bcid.ExpeditionMinter.getExpeditionId(ExpeditionMinter.java:204)
    at biocode.fims.bcid.ExpeditionMinter.attachReferenceToExpedition(ExpeditionMinter.java:128)
    at biocode.fims.rest.services.rest.ExpeditionService.associate(ExpeditionService.java:294)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
    at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
    at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
    at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)
    at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
    at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
    at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
    at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
    at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
    at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
    at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
    at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
    at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
    at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
    at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:471)
    at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:425)
    at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:383)
    at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:336)
    at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:223)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
    at services.RedirectFilter.doFilter(RedirectFilter.java:29)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
    at biocode.fims.rest.filters.ClickJackFilter.doFilter(ClickJackFilter.java:28)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
    at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
    at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
    at org.eclipse.jetty.server.Server.handle(Server.java:497)
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:313)
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
    at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:626)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:546)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by jdeck88** [comment]
Thanks for the heads up.

A 400 (BAD_REQUEST) code and a human readable message is better than a 500
code and a stacktrace...

i just added this for the associate function in cases where bcid or
expeditionCode or null...  (but will wait to deploy later).


On Thu, Mar 10, 2016 at 9:07 PM, Philip Kahn <notifications@github.com>
wrote:

> @jdeck88 <https://github.com/jdeck88> , head's-up, getting HTTP 500 error
> from FIMS, with the following stack trace if a null or empty bcid is
> posted:
>
> java.lang.NullPointerException
>     at biocode.fims.bcid.ExpeditionMinter.getExpeditionId(ExpeditionMinter.java:204)
>     at biocode.fims.bcid.ExpeditionMinter.attachReferenceToExpedition(ExpeditionMinter.java:128)
>     at biocode.fims.rest.services.rest.ExpeditionService.associate(ExpeditionService.java:294)
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke(Method.java:606)
>     at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
>     at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
>     at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
>     at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)
>     at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
>     at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
>     at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
>     at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
>     at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
>     at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
>     at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
>     at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
>     at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
>     at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
>     at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
>     at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
>     at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
>     at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:471)
>     at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:425)
>     at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:383)
>     at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:336)
>     at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:223)
>     at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800)
>     at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
>     at services.RedirectFilter.doFilter(RedirectFilter.java:29)
>     at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
>     at biocode.fims.rest.filters.ClickJackFilter.doFilter(ClickJackFilter.java:28)
>     at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
>     at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
>     at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
>     at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
>     at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
>     at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
>     at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
>     at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
>     at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
>     at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
>     at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
>     at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
>     at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
>     at org.eclipse.jetty.server.Server.handle(Server.java:497)
>     at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:313)
>     at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
>     at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
>     at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:626)
>     at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:546)
>     at java.lang.Thread.run(Thread.java:745)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AmphibiaWeb/amphibian-disease-tracker/issues/62#issuecomment-195190624>
> .
>



-- 
John Deck
(541) 914-4739
